oTees/Models/Shirt.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace oTees.Models
{
    public class Shirt
    {
        public int ShirtID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public virtual ICollection<Image> Images { get; set; }

        public int UserID { get; set; }
        public virtual User User { get; set; }
    }
}

oTees/Controllers/ShirtController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using oTees.Models;
using oTees.DAL;
using oTees.Repositories;
using oTees.Services;

namespace oTees.Controllers
{
    public class ShirtController : Controller
    {
        private IShirtRepository shirtRepo = new ShirtRepository();
        private IUserRepository userRepo = new UserRepository();
        private OteesDBContext db = new OteesDBContext();

        //
        // GET: /Shirt/

        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        //
        // GET: /Shirt/Details/5

        public ActionResult Details(int id = 0)
        {
            Shirt shirt = shirtRepo.Get(id);
            if (shirt == null)
            {
                return HttpNotFound();
            }
            return View(shirt);
        }

        //
        // GET: /Shirt/Create

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Shirt/Create

        [HttpPost]
        [Authorize]
        public ActionResult Create(Shirt shirt)
        {
            String userName = User.Identity.Name;

            User user = userRepo.GetUserByEmail(userName);

            if (ModelState.IsValid)
            {
                shirtRepo.Add(shirt, user);
                return RedirectToAction("Index");
            }

            return View(shirt);
        }

        //
        // GET: /Shirt/Edit/5

        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            Shirt shirt = shirtRepo.Get(id);
            if (shirt == null)
            {
                return HttpNotFound();
            }
            return View(shirt);
        }

        //
        // POST: /Shirt/Edit/5

        [HttpPost]
        [Authorize]
        public ActionResult Edit(Shirt shirt)
        {
            if (ModelState.IsValid)
            {
                shirtRepo.Update(shirt);
                return RedirectToAction("Index");
            }
            return View(shirt);
        }

        //
        // GET: /Shirt/Delete/5

        [RoleAuthorize(Roles = "Admin")]
        public ActionResult Delete(int id = 0)
        {
            Shirt shirt = shirtRepo.Get(id);
            if (shirt == null)
            {
                return HttpNotFound();
            }
            return View(shirt);
        }

        //
        // POST: /Shirt/Delete/5

        [RoleAuthorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            shirtRepo.Remove(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

oTees/Views/Shirt/Create.cshtml
@model oTees.Models.Shirt

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Shirt</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

oTees/Views/Shirt/Delete.cshtml
@model oTees.Models.Shirt

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Shirt</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

oTees/Views/Shirt/Details.cshtml
@model oTees.Models.Shirt

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<img src="http://placehold.it/350x200">

<fieldset>
    <legend>Shirt</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ShirtID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

oTees/Views/Shirt/Edit.cshtml
@model oTees.Models.Shirt

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Shirt</legend>

        @Html.HiddenFor(model => model.ShirtID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

oTees/Views/Shirt/Index.cshtml
@model IEnumerable<oTees.Models.Shirt>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Shirt")
</p>

<ul class="block-grid three-up">

    @foreach (var item in Model)
    {
        <li class="shirt-entry">
            <a href="@Url.Action("Details", "Shirt", new { id=item.ShirtID })" class="th"><img src="http://placehold.it/350x200"></a>
                @Html.DisplayFor(modelItem => item.Name)
            <p>
                @Html.ActionLink("Edit", "Edit", "Shirt", new { id=item.ShirtID }, null) |
                @Html.ActionLink("Delete", "Delete", "Shirt", new { id=item.ShirtID }, null)
            </p>
        </li>
    }
</ul>